# Generated by Django 3.1.4 on 2020-12-29 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostHome4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_baslik', models.CharField(max_length=255)),
                ('who_aciklama', models.TextField()),
                ('who_fotograf', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Story_Bolumu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_baslik', models.CharField(max_length=255)),
                ('story_aciklama', models.TextField()),
                ('story_fotograf', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PostHome3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik_1', models.CharField(max_length=255)),
                ('aciklama_1', models.TextField()),
                ('baslik_2', models.CharField(max_length=255)),
                ('aciklama_2', models.TextField()),
                ('baslik_3', models.CharField(max_length=255)),
                ('aciklama_3', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostHome2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_isim_soyisim', models.CharField(max_length=225)),
                ('cv_Meslek', models.CharField(default='blog', max_length=225)),
                ('cv_fotograf_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
