# Generated by Django 3.1.4 on 2021-01-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthome2',
            name='cv_fotograf_1',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
