# Generated by Django 3.1.4 on 2020-12-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Bolumu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_isim', models.CharField(max_length=255)),
                ('work_fotograf', models.ImageField(blank=True, null=True, upload_to='')),
                ('work_fotograf_3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
