# Generated by Django 3.1.4 on 2020-12-29 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0002_work_bolumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_bolumu',
            name='work_alt_baslik',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
