# Generated by Django 3.1.4 on 2020-12-29 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_work_bolumu_work_alt_baslik'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_bolumu',
            name='work_aciklama',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work_bolumu',
            name='work_alt_baslik',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
