# Generated by Django 3.1.4 on 2021-01-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0004_auto_20201229_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebLogoName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_isim', models.CharField(max_length=225)),
                ('web_logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
