# Generated by Django 3.1.4 on 2021-01-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0005_weblogoname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posthome2',
            old_name='cv_Meslek',
            new_name='cv_job',
        ),
        migrations.RenameField(
            model_name='posthome2',
            old_name='cv_isim_soyisim',
            new_name='cv_name_surname',
        ),
        migrations.RenameField(
            model_name='posthome2',
            old_name='cv_fotograf_1',
            new_name='cv_photo',
        ),
        migrations.RenameField(
            model_name='posthome3',
            old_name='aciklama_1',
            new_name='content_1',
        ),
        migrations.RenameField(
            model_name='posthome3',
            old_name='aciklama_2',
            new_name='content_2',
        ),
        migrations.RenameField(
            model_name='posthome3',
            old_name='aciklama_3',
            new_name='content_3',
        ),
        migrations.RenameField(
            model_name='posthome3',
            old_name='baslik_1',
            new_name='title_1',
        ),
        migrations.RenameField(
            model_name='posthome3',
            old_name='baslik_2',
            new_name='title_2',
        ),
        migrations.RenameField(
            model_name='posthome3',
            old_name='baslik_3',
            new_name='title_3',
        ),
        migrations.RenameField(
            model_name='posthome4',
            old_name='who_aciklama',
            new_name='who_content',
        ),
        migrations.RenameField(
            model_name='posthome4',
            old_name='who_fotograf',
            new_name='who_photo',
        ),
        migrations.RenameField(
            model_name='posthome4',
            old_name='who_baslik',
            new_name='who_title',
        ),
        migrations.RenameField(
            model_name='story_bolumu',
            old_name='story_aciklama',
            new_name='story_content',
        ),
        migrations.RenameField(
            model_name='story_bolumu',
            old_name='story_fotograf',
            new_name='story_photo',
        ),
        migrations.RenameField(
            model_name='story_bolumu',
            old_name='story_baslik',
            new_name='story_title',
        ),
        migrations.RenameField(
            model_name='weblogoname',
            old_name='web_isim',
            new_name='web_name',
        ),
        migrations.RenameField(
            model_name='work_bolumu',
            old_name='work_aciklama',
            new_name='work_content',
        ),
        migrations.RenameField(
            model_name='work_bolumu',
            old_name='work_fotograf',
            new_name='work_content_photo',
        ),
        migrations.RenameField(
            model_name='work_bolumu',
            old_name='work_isim',
            new_name='work_name',
        ),
        migrations.RenameField(
            model_name='work_bolumu',
            old_name='work_fotograf_3',
            new_name='work_photo',
        ),
        migrations.RenameField(
            model_name='work_bolumu',
            old_name='work_alt_baslik',
            new_name='work_sub_title',
        ),
        migrations.AddField(
            model_name='work_bolumu',
            name='work_sub_title_black',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
