# Generated by Django 3.1.4 on 2021-01-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0006_auto_20210102_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_bolumu',
            old_name='work_content_photo',
            new_name='work_index_photo',
        ),
    ]
