# Generated by Django 3.1.4 on 2021-01-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0007_auto_20210102_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_bolumu',
            old_name='work_photo',
            new_name='work_article_photo',
        ),
    ]
