# Generated by Django 3.1.4 on 2021-01-02 20:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0008_auto_20210102_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthome3',
            name='content_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
