# Generated by Django 3.1.4 on 2021-01-02 20:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0009_auto_20210102_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthome3',
            name='content_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posthome3',
            name='content_3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posthome4',
            name='who_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story_bolumu',
            name='story_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work_bolumu',
            name='work_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
