# Generated by Django 3.1.4 on 2021-01-02 21:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portapp', '0010_auto_20210102_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story_Bolumu',
            new_name='AboutMeSection',
        ),
        migrations.RenameModel(
            old_name='PostHome2',
            new_name='HomeSection',
        ),
        migrations.RenameModel(
            old_name='PostHome3',
            new_name='MyServicesSection',
        ),
        migrations.RenameModel(
            old_name='PostHome4',
            new_name='StorySection',
        ),
        migrations.RenameModel(
            old_name='Work_Bolumu',
            new_name='WorkSection',
        ),
        migrations.RenameField(
            model_name='aboutmesection',
            old_name='story_content',
            new_name='who_content',
        ),
        migrations.RenameField(
            model_name='aboutmesection',
            old_name='story_photo',
            new_name='who_photo',
        ),
        migrations.RenameField(
            model_name='aboutmesection',
            old_name='story_title',
            new_name='who_title',
        ),
        migrations.RenameField(
            model_name='storysection',
            old_name='who_content',
            new_name='story_content',
        ),
        migrations.RenameField(
            model_name='storysection',
            old_name='who_photo',
            new_name='story_photo',
        ),
        migrations.RenameField(
            model_name='storysection',
            old_name='who_title',
            new_name='story_title',
        ),
    ]
