# Generated by Django 3.1.4 on 2021-01-02 21:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0011_auto_20210103_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmesection',
            name='who_photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='cv_photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='storysection',
            name='story_photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='weblogoname',
            name='web_logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='worksection',
            name='work_article_photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='worksection',
            name='work_index_photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=''),
        ),
    ]
