# Generated by Django 3.1.4 on 2021-01-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0013_auto_20210103_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_linked', models.CharField(blank=True, max_length=300)),
                ('footer_github', models.CharField(blank=True, max_length=300)),
                ('footer_instagram', models.CharField(blank=True, max_length=300)),
                ('footer_facebook', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
