# Generated by Django 3.1.4 on 2021-01-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0014_footersection'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='footer_email',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
