# Generated by Django 3.1.4 on 2021-01-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0015_footersection_footer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblogoname',
            name='web_name',
            field=models.CharField(help_text='This is your site title', max_length=225),
        ),
    ]
