# Generated by Django 3.1.4 on 2021-01-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0016_auto_20210103_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmesection',
            name='who_title',
            field=models.CharField(help_text='Who I am; under the title', max_length=255),
        ),
        migrations.AlterField(
            model_name='storysection',
            name='story_title',
            field=models.CharField(help_text='This is My Story; under the title', max_length=255),
        ),
    ]
